#!/usr/bin/env python3
"""Generate the bundled learning-card pronunciation fallback.

Requires Kokoro 0.9.4, misaki[ja], soundfile and ffmpeg. The generated MP3
files are intentionally small and are played before Android TTS is considered.
"""

from __future__ import annotations

import hashlib
import json
import re
import subprocess
import tempfile
from pathlib import Path

import soundfile as sf
from kokoro import KPipeline


ROOT = Path(__file__).resolve().parents[1]
APP_JS = ROOT / "app/src/main/assets/web/app.js"
AUDIO_DIR = ROOT / "app/src/main/assets/web/audio/pronunciation"
MANIFEST = ROOT / "app/src/main/assets/web/pronunciation-audio.js"


def kana_entries() -> list[tuple[str, str]]:
    source = APP_JS.read_text(encoding="utf-8")
    group_source = source[source.index("const GROUPS = [") : source.index("const DEFAULT_DATA")]
    matches = re.findall(
        r'\[\s*"([^"]+)",\s*"([^"]+)",\s*"([^"]+)"(?:,\s*"[^"]+")*\s*\]',
        group_source,
    )
    result: list[tuple[str, str]] = []
    seen: set[tuple[str, str]] = set()
    for hiragana, katakana, _romaji in matches:
        pair = (hiragana, katakana)
        if pair not in seen:
            seen.add(pair)
            result.append(pair)
    if len(result) < 100:
        raise RuntimeError(f"Expected at least 100 Kana entries, found {len(result)}")
    return result


def learning_card_speech() -> list[str]:
    script = r"""
import { VOCABULARY } from './app/src/main/assets/web/vocabulary.js';
import { KANJI } from './app/src/main/assets/web/kanji.js';
import { KANJI_VOCABULARY } from './app/src/main/assets/web/kanji-vocabulary.js';
const speech = [
  ...VOCABULARY.map((word) => word.kana),
  ...KANJI.map((kanji) => kanji.readings.replaceAll('・', '、')),
  ...KANJI_VOCABULARY.map((word) => word.reading),
];
console.log(JSON.stringify([...new Set(speech)]));
"""
    completed = subprocess.run(
        ["node", "--input-type=module", "-e", script],
        cwd=ROOT,
        check=True,
        capture_output=True,
        text=True,
    )
    return json.loads(completed.stdout)


def create_recording(pipeline: KPipeline, speech: str, destination: Path, temporary_dir: Path) -> None:
    digest = destination.stem
    wav_path = temporary_dir / f"{digest}.wav"
    generator = pipeline(f"{speech}。", voice="jf_alpha", speed=0.82)
    for _graphemes, _phonemes, audio in generator:
        sf.write(wav_path, audio, 24_000)
        break
    else:
        raise RuntimeError(f"No audio generated for {speech}")

    subprocess.run(
        [
            "ffmpeg",
            "-hide_banner",
            "-loglevel",
            "error",
            "-y",
            "-i",
            str(wav_path),
            "-af",
            "silenceremove=start_periods=1:start_duration=0.01:start_threshold=-55dB:stop_periods=-1:stop_duration=0.08:stop_threshold=-55dB,apad=pad_dur=0.08",
            "-ar",
            "24000",
            "-ac",
            "1",
            "-b:a",
            "40k",
            str(destination),
        ],
        check=True,
    )


def main() -> None:
    entries = kana_entries()
    card_speech = learning_card_speech()
    AUDIO_DIR.mkdir(parents=True, exist_ok=True)
    pipeline = KPipeline(lang_code="j", repo_id="hexgrad/Kokoro-82M")
    manifest: dict[str, str] = {}

    with tempfile.TemporaryDirectory(prefix="kana-garten-audio-") as temporary:
        temporary_dir = Path(temporary)
        for hiragana, katakana in entries:
            digest = hashlib.sha256(hiragana.encode("utf-8")).hexdigest()[:12]
            filename = f"{digest}.mp3"
            destination = AUDIO_DIR / filename
            manifest[hiragana] = f"/audio/pronunciation/{filename}"
            manifest[katakana] = f"/audio/pronunciation/{filename}"
            if destination.exists() and destination.stat().st_size > 1_000:
                continue
            create_recording(pipeline, hiragana, destination, temporary_dir)

        for index, speech in enumerate(card_speech, start=1):
            if speech in manifest:
                continue
            digest = hashlib.sha256(speech.encode("utf-8")).hexdigest()[:12]
            filename = f"{digest}.mp3"
            destination = AUDIO_DIR / filename
            manifest[speech] = f"/audio/pronunciation/{filename}"
            if destination.exists() and destination.stat().st_size > 1_000:
                continue
            create_recording(pipeline, speech, destination, temporary_dir)
            print(f"[{index:04d}/{len(card_speech):04d}] {speech}", flush=True)

    serialized = json.dumps(manifest, ensure_ascii=False, separators=(",", ":"))
    MANIFEST.write_text(
        "// Generated by tools/generate_pronunciation_audio.py with hexgrad/Kokoro-82M (Apache-2.0).\n"
        f"export const BUNDLED_PRONUNCIATION_AUDIO = Object.freeze({serialized});\n",
        encoding="utf-8",
    )
    print(
        f"Generated {len(set(manifest.values()))} recordings and "
        f"{len(manifest)} lookup entries."
    )


if __name__ == "__main__":
    main()
